event_1_arm_1 = [
    'record_id',
    'redcap_survey_identifier',
    'demographics_and_injury_characteristics_timestamp',
    'id_lab',
    'group',
    'centrum',
    'woonplaats',
    'email_yes_no',
    'email',
    'dataofinjury',
    'age',
    'gender',
    'ct_abn',
    'marshall',
    'concl_radio_ct',
    'alcohol_ongeval',
    'eenheden_alc',
    'drugs_ongeval',
    'drugs_ongeval_hoeveel',
    'demographics_and_injury_characteristics_complete',
    'trauma_capitis',
    'tijd_ongeval',
    'v1_datum',
    'afnametijdv1',
    'v2_afname',
    'datumv2',
    'gcs',
    'extra_opm_gcs',
    'loc',
    'pta',
    'ongevalsmechanisme',
    'elektrischefiets',
    'helm',
    'opname_yes_no',
    'opname_dagen',
    'ais_hoofd',
    'extracran',
    'iss_total',
    'ctcwk1',
    'ctcwk2',
    'operatie1',
    'operatie2',
    'ethanol',
    'antistol',
    'overig_antistol_what',
    'inflamm_vg',
    'inflamm_vg2',
    'med_inflamm1',
    'med_inflamm2',
    'ht_dossier',
    'dm_dossier',
    'hyperlip_dossier',
    'copd_astma_dossier',
    'cortico_dossier',
    'eeg_deelname',
    'datumeeg1',
    'tijdeeg1',
    'datumeeg2',
    'ptascorelijst',
    'mrideelname',
    'datummri',
    'nummermri',
    'cortisoldeelname',
    'datum_haar',
    'speeksel',
    'injury_characteristics_extra_complete',
]

event_2_arm_1 = [
    'vragenlijsten_deel_1_timestamp',
    'leeftijd',
    'handedness',
    'edu',
    'werk_studie',
    'werk_functie',
    'woonsituatie',
    'vrije_tijd',
    'sport_uren',
    'meds',
    'meds_type',
    'roken',
    'roken_hoeveel',
    'alcohol',
    'alcohol_hoeveel',
    'drugs',
    'drugs_hoeveel',
    'eerder_tbi',
    'lichaam',
    'lichaam_kl',
    'lichaam_behandeling',
    'lichaam_behandelaar',
    'psych',
    'psych_kl',
    'psych_behandeling',
    'psych_behandelaar',
    'psych_opname',
    'tkl_hp_voor',
    'tkl_hp_na',
    'tkl_duizel_voor',
    'tkl_duizel_na',
    'tkl_evenw_voor',
    'tkl_evenw_na',
    'tkl_oor_voor',
    'tkl_oor_na',
    'tkl_gehoor_voor',
    'tkl_gehoor_na',
    'tkl_slaap_voor',
    'tkl_slaap_na',
    'tkl_inslaap_voor',
    'tkl_inslaap_na',
    'tkl_doorslaap_voor',
    'tkl_doorslaap_na',
    'tkl_moe_voor',
    'tkl_moe_na',
    'tkl_vergeet_voor',
    'tkl_vergeet_na',
    'tkl_conc_voor',
    'tkl_conc_na',
    'tkl_traag_voor',
    'tkl_traag_na',
    'tkl_prik_voor',
    'tkl_prik_na',
    'tkl_lawaai_voor',
    'tkl_lawaai_na',
    'tkl_alc_voor',
    'tkl_alc_na',
    'tkl_angst_voor',
    'tkl_angst_na',
    'tkl_droog_voor',
    'tkl_droog_na',
    'tkl_nekpijn_voor',
    'tkl_nekpijn_na',
    'tkl_nekstijf_voor',
    'tkl_nekstijf_na',
    'tkl_arm_voor',
    'tkl_arm_na',
    'tkl_jeuk_voor',
    'tkl_jeuk_na',
    'neo_tobber',
    'neo_mensen',
    'neo_dagdromen',
    'neo_hoffelijk',
    'neo_spullen',
    'neo_mindere',
    'neo_lach',
    'neo_manier',
    'neo_mening',
    'neo_oppep',
    'neo_eronderdoor',
    'neo_opgewekt_persoon',
    'neo_intrigeer',
    'neo_egoistisch',
    'neo_systematisch',
    'neo_eenzaam',
    'neo_leuk_praten',
    'neo_leerlingen',
    'neo_samenwerken',
    'neo_gewetensvol',
    'neo_zenuwachtig',
    'neo_beleven',
    'neo_poezie',
    'neo_cynisch',
    'neo_doelen',
    'neo_waardeloos',
    'neo_alleen_doen',
    'neo_gerechten',
    'neo_gebruiken',
    'neo_verknoei',
    'neo_zorgelijk',
    'neo_energie',
    'neo_omgeving',
    'neo_graag_mogen',
    'neo_doel_bereik',
    'neo_kwaad_behandel',
    'neo_levendig',
    'neo_moreel',
    'neo_koel',
    'neo_belofte',
    'neo_opgeven',
    'neo_optimist',
    'neo_rilling',
    'neo_zakelijk',
    'neo_betrouwbaar',
    'neo_verdrietig',
    'neo_jachtig',
    'neo_universum',
    'neo_attent',
    'neo_productief',
    'neo_hulpeloos',
    'neo_actief',
    'neo_intellectueel',
    'neo_merken',
    'neo_op_orde',
    'neo_schaam',
    'neo_eigen_gang',
    'neo_theorie',
    'neo_manipuleren',
    'neo_uitblinken',
    'hads_gespannen',
    'hads_geniet',
    'hads_angst',
    'hads_vrolijk',
    'hads_ongerust',
    'hads_opgewekt',
    'hads_ontspan',
    'hads_moeizaam',
    'hads_benauwd',
    'hads_uiterlijk',
    'hads_rusteloos',
    'hads_verheug',
    'hads_paniek',
    'hads_boek',
    'vragenlijsten_deel_1_complete',
]

event_3_arm_1 = [
    'vragenlijsten_deel_2_timestamp',
    'tkl_hp_voor_v2',
    'tkl_hp_na_v2',
    'tkl_duizel_voor_v2',
    'tkl_duizel_na_v2',
    'tkl_evenw_voor_v2',
    'tkl_evenw_na_v2',
    'tkl_oor_voor_v2',
    'tkl_oor_na_v2',
    'tkl_gehoor_voor_v2',
    'tkl_gehoor_na_v2',
    'tkl_slaap_voor_v2',
    'tkl_slaap_na_v2',
    'tkl_inslaap_voor_v2',
    'tkl_inslaap_na_v2',
    'tkl_doorslaap_voor_v2',
    'tkl_doorslaap_na_v2',
    'tkl_moe_voor_v2',
    'tkl_moe_na_v2',
    'tkl_vergeet_voor_v2',
    'tkl_vergeet_na_v2',
    'tkl_conc_voor_v2',
    'tkl_conc_na_v2',
    'tkl_traag_voor_v2',
    'tkl_traag_na_v2',
    'tkl_prik_voor_v2',
    'tkl_prik_na_v2',
    'tkl_lawaai_voor_v2',
    'tkl_lawaai_na_v2',
    'tkl_alc_voor_v2',
    'tkl_alc_na_v2',
    'tkl_angst_voor_v2',
    'tkl_angst_na_v2',
    'tkl_droog_voor_v2',
    'tkl_droog_na_v2',
    'tkl_nekpijn_voor_v2',
    'tkl_nekpijn_na_v2',
    'tkl_nekstijf_voor_v2',
    'tkl_nekstijf_na_v2',
    'tkl_arm_voor_v2',
    'tkl_arm_na_v2',
    'tkl_jeuk_voor_v2',
    'tkl_jeuk_na_v2',
    'hads_gespannen_v2',
    'hads_geniet_v2',
    'hads_angst_v2',
    'hads_vrolijk_v2',
    'hads_ongerust_v2',
    'hads_opgewekt_v2',
    'hads_ontspan_v2',
    'hads_moeizaam_v2',
    'hads_benauwd_v2',
    'hads_uiterlijk_v2',
    'hads_rusteloos_v2',
    'hads_verheug_v2',
    'hads_paniek_v2',
    'hads_boek_v2',
    'gose_opdrachten',
    'gose_hulp',
    'gose_hulp_vaak',
    'gose_onafh',
    'gose_boodschap',
    'gose_boodschap_voor',
    'gose_buurt',
    'gose_buurt_voor',
    'gose_werk_school',
    'gose_arbeid',
    'gose_werk_voor',
    'gose_sociaal',
    'gose_beperk_vrije_tijd',
    'gose_omgang',
    'gose_psych_prob',
    'gose_psych_prob_vaak',
    'gose_psych_prob_anders',
    'gose_klachten',
    'gose_klachten_voor',
    'gose_klachten_oorzaak',
    'ies_denken_v2',
    'ies_van_streek_v2',
    'ies_geheugen_ban_v2',
    'ies_slaap_v2',
    'ies_gevoelens_v2',
    'ies_droom_v2',
    'ies_uit_de_weg_v2',
    'ies_niet_echt_v2',
    'ies_praten_v2',
    'ies_beelden_v2',
    'ies_andere_dingen_v2',
    'ies_rekening_v2',
    'ies_niet_denken_v2',
    'ies_herinnering_v2',
    'ies_verdoofd_v2',
    'vragenlijsten_deel_2_complete',
]

event_2_arm_3 = [
    'vragenlijsten_deel_1_voor_gezonde_proefpersonen_timestamp',
    'leeftijd_hc',
    'handedness_hc',
    'edu_hc',
    'werk_studie_hc',
    'werk_functie_hc',
    'woonsituatie_hc',
    'vrije_tijd_hc',
    'sport_uren_hc',
    'meds_hc',
    'meds_type_hc',
    'roken_hc',
    'roken_hoeveel_hc',
    'alcohol_hc',
    'alcohol_hoeveel_hc',
    'drugs_hc',
    'drugs_hoeveel_hc',
    'lichaam_hc',
    'lichaam_kl_hc',
    'lichaam_behandeling_hc',
    'lichaam_behandelaar_hc',
    'psych_hc',
    'psych_kl_hc',
    'psych_behandeling_hc',
    'psych_behandelaar_hc',
    'psych_opname_hc',
    'tkl_hp_hc',
    'tkl_duizel_hc',
    'tkl_evenw_hc',
    'tkl_oor_hc',
    'tkl_gehoor_hc',
    'tkl_slaap_hc',
    'tkl_inslaap_hc',
    'tkl_doorslaap_hc',
    'tkl_moe_hc',
    'tkl_vergeet_hc',
    'tkl_conc_hc',
    'tkl_traag_hc',
    'tkl_prik_hc',
    'tkl_lawaai_hc',
    'tkl_alc_hc',
    'tkl_angst_tkl_hc',
    'tkl_droog_hc',
    'tkl_nekpijn_hc',
    'tkl_nekstijf_hc',
    'tkl_arm_hc',
    'tkl_jeuk_hc',
    'neo_tobber_hc',
    'neo_mensen_hc',
    'neo_dagdromen_hc',
    'neo_hoffelijk_hc',
    'neo_spullen_hc',
    'neo_mindere_hc',
    'neo_lach_hc',
    'neo_manier_hc',
    'neo_mening_hc',
    'neo_oppep_hc',
    'neo_eronderdoor_hc',
    'neo_opgewekt_persoon_hc',
    'neo_intrigeer_hc',
    'neo_egoistisch_hc',
    'neo_systematisch_hc',
    'neo_eenzaam_hc',
    'neo_leuk_praten_hc',
    'neo_leerlingen_hc',
    'neo_samenwerken_hc',
    'neo_gewetensvol_hc',
    'neo_zenuwachtig_hc',
    'neo_beleven_hc',
    'neo_poezie_hc',
    'neo_cynisch_hc',
    'neo_doelen_hc',
    'neo_waardeloos_hc',
    'neo_alleen_doen_hc',
    'neo_gerechten_hc',
    'neo_gebruiken_hc',
    'neo_verknoei_hc',
    'neo_zorgelijk_hc',
    'neo_energie_hc',
    'neo_omgeving_hc',
    'neo_graag_mogen_hc',
    'neo_doel_bereik_hc',
    'neo_kwaad_behandel_hc',
    'neo_levendig_hc',
    'neo_moreel_hc',
    'neo_koel_hc',
    'neo_belofte_hc',
    'neo_opgeven_hc',
    'neo_optimist_hc',
    'neo_rilling_hc',
    'neo_zakelijk_hc',
    'neo_betrouwbaar_hc',
    'neo_verdrietig_hc',
    'neo_jachtig_hc',
    'neo_universum_hc',
    'neo_attent_hc',
    'neo_productief_hc',
    'neo_hulpeloos_hc',
    'neo_actief_hc',
    'neo_intellectueel_hc',
    'neo_merken_hc',
    'neo_op_orde_hc',
    'neo_schaam_hc',
    'neo_eigen_gang_hc',
    'neo_theorie_hc',
    'neo_manipuleren_hc',
    'neo_uitblinken_hc',
    'hads_gespannen_hc',
    'hads_geniet_hc',
    'hads_angst_hc',
    'hads_vrolijk_hc',
    'hads_ongerust_hc',
    'hads_opgewekt_hc',
    'hads_ontspan_hc',
    'hads_moeizaam_hc',
    'hads_benauwd_hc',
    'hads_uiterlijk_hc',
    'hads_rusteloos_hc',
    'hads_verheug_hc',
    'hads_paniek_hc',
    'hads_boek_hc',
    'vragenlijsten_deel_1_voor_gezonde_proefpersonen_complete',
]

event_3_arm_3 = [
    'tkl_hp_v2_hc',
    'tkl_duizel_v2_hc',
    'tkl_evenw_v2_hc',
    'tkl_oor_v2_hc',
    'tkl_gehoor_v2_hc',
    'tkl_slaap_tkl_v2_hc',
    'tkl_inslaap_v2_hc',
    'tkl_doorslaap_v2_hc',
    'tkl_moe_v2_hc',
    'tkl_vergeet_v2_hc',
    'tkl_conc_v2_hc',
    'tkl_traag_v2_hc',
    'tkl_prik_v2_hc',
    'tkl_lawaai_v2_hc',
    'tkl_alc_v2_hc',
    'tkl_angst_tkl_v2_hc',
    'tkl_droog_v2_hc',
    'tkl_nekpijn_v2_hc',
    'tkl_nekstijf_v2_hc',
    'tkl_arm_v2_hc',
    'tkl_jeuk_v2_hc',
    'hads_gespannen_v2_hc',
    'hads_geniet_v2_hc',
    'hads_angst_v2_hc',
    'hads_vrolijk_v2_hc',
    'hads_ongerust_v2_hc',
    'hads_opgewekt_v2_hc',
    'hads_ontspan_v2_hc',
    'hads_moeizaam_v2_hc',
    'hads_benauwd_v2_hc',
    'hads_uiterlijk_v2_hc',
    'hads_rusteloos_v2_hc',
    'hads_verheug_v2_hc',
    'hads_paniek_v2_hc',
    'hads_boek_v2_hc',
    'gose_opdrachten_hc',
    'gose_hulp_hc',
    'gose_hulp_vaak_hc',
    'gose_onafh_hc',
    'gose_boodschap_hc',
    'gose_boodschap_voor_hc',
    'gose_buurt_hc',
    'gose_buurt_voor_hc',
    'gose_werk_school_hc',
    'gose_arbeid_hc',
    'gose_werk_voor_hc',
    'gose_sociaal_hc',
    'gose_beperk_vrije_tijd_hc',
    'gose_omgang_hc',
    'gose_psych_prob_hc',
    'gose_psych_prob_vaak_hc',
    'gose_psych_prob_anders_hc',
    'gose_klachten_hc',
    'gose_klachten_voor_hc',
    'gose_klacht_oorzaak_hc',
    'vragenlijsten_deel_2_voor_gezonde_proefpersonen_complete',
    'vragenlijsten_deel_2_voor_gezonde_proefpersonen_timestamp',
]

hads_2_weeks_mtbi = [
    'hads_gespannen',
    'hads_geniet',
    'hads_angst',
    'hads_vrolijk',
    'hads_ongerust',
    'hads_opgewekt',
    'hads_ontspan',
    'hads_moeizaam',
    'hads_benauwd',
    'hads_uiterlijk',
    'hads_rusteloos',
    'hads_verheug',
    'hads_paniek',
    'hads_boek'
]

hads_6_months_mtbi = [
    'hads_gespannen_v2',
    'hads_geniet_v2',
    'hads_angst_v2',
    'hads_vrolijk_v2',
    'hads_ongerust_v2',
    'hads_opgewekt_v2',
    'hads_ontspan_v2',
    'hads_moeizaam_v2',
    'hads_benauwd_v2',
    'hads_uiterlijk_v2',
    'hads_rusteloos_v2',
    'hads_verheug_v2',
    'hads_paniek_v2',
    'hads_boek_v2',
]

hads_2_weeks_hc = [
    'hads_gespannen_hc',
    'hads_geniet_hc',
    'hads_angst_hc',
    'hads_vrolijk_hc',
    'hads_ongerust_hc',
    'hads_opgewekt_hc',
    'hads_ontspan_hc',
    'hads_moeizaam_hc',
    'hads_benauwd_hc',
    'hads_uiterlijk_hc',
    'hads_rusteloos_hc',
    'hads_verheug_hc',
    'hads_paniek_hc',
    'hads_boek_hc',
]

hads_6_months_hc = [
    'hads_gespannen_v2_hc',
    'hads_geniet_v2_hc',
    'hads_angst_v2_hc',
    'hads_vrolijk_v2_hc',
    'hads_ongerust_v2_hc',
    'hads_opgewekt_v2_hc',
    'hads_ontspan_v2_hc',
    'hads_moeizaam_v2_hc',
    'hads_benauwd_v2_hc',
    'hads_uiterlijk_v2_hc',
    'hads_rusteloos_v2_hc',
    'hads_verheug_v2_hc',
    'hads_paniek_v2_hc',
    'hads_boek_v2_hc',
]

recoding_hads = {
    float(1.0): 0,
    float(2.0): 1,
    float(3.0): 2,
    float(4.0): 3,
}

recoding_HISC = {
    float(1.0): 0,
    float(2.0): 1,
    float(3.0): 2,
}

recoding_ies = {
    float(1.0): 0,
    float(2.0): 1,
    float(4): 5
}

recoding_general = {
    'group': {3:0},
    'gender': {1:0, 2:1},
    'centre': {1:0, 2:1},
    'gcs': {1: 15, 2:14, 3:13},
    'loc': {1:0, 2:1, 3:2},
    'pta': {1:0, 2:1, 3:2},
    'medications_use': {2:0},
    'smoker': {2:0},
    'alcohol_use': {2:0},
    'drug_use': {2:0},
    'previous_tbi': {2:0},
    'physical_symptoms': {2:0},
    'physical_symptoms_treatment': {2:0},
    'psychological_symptoms': {2:0},
    'psychological_symptoms_treatment': {2:0},
}

HISC_2_weeks_TBI_pre = [
    'tkl_hp_voor',
    'tkl_duizel_voor',
    'tkl_evenw_voor',
    'tkl_oor_voor',
    'tkl_gehoor_voor',
    'tkl_slaap_voor',
    'tkl_inslaap_voor',
    'tkl_doorslaap_voor',
    'tkl_moe_voor',
    'tkl_vergeet_voor',
    'tkl_conc_voor',
    'tkl_traag_voor',
    'tkl_prik_voor',
    'tkl_lawaai_voor',
    'tkl_alc_voor',
    'tkl_angst_voor',
    'tkl_droog_voor',
    'tkl_nekpijn_voor',
    'tkl_nekstijf_voor',
    'tkl_arm_voor',
    'tkl_jeuk_voor',
]

HISC_2_weeks_TBI_post = [
    'tkl_hp_na',
    'tkl_duizel_na',
    'tkl_evenw_na',
    'tkl_oor_na',
    'tkl_gehoor_na',
    'tkl_slaap_na',
    'tkl_inslaap_na',
    'tkl_doorslaap_na',
    'tkl_moe_na',
    'tkl_vergeet_na',
    'tkl_conc_na',
    'tkl_traag_na',
    'tkl_prik_na',
    'tkl_lawaai_na',
    'tkl_alc_na',
    'tkl_angst_na',
    'tkl_droog_na',
    'tkl_nekpijn_na',
    'tkl_nekstijf_na',
    'tkl_arm_na',
    'tkl_jeuk_na',
]

HISC_6_months_TBI_pre = [
    'tkl_hp_voor_v2',
    'tkl_duizel_voor_v2',
    'tkl_evenw_voor_v2',
    'tkl_oor_voor_v2',
    'tkl_gehoor_voor_v2',
    'tkl_slaap_voor_v2',
    'tkl_inslaap_voor_v2',
    'tkl_doorslaap_voor_v2',
    'tkl_moe_voor_v2',
    'tkl_vergeet_voor_v2',
    'tkl_conc_voor_v2',
    'tkl_traag_voor_v2',
    'tkl_prik_voor_v2',
    'tkl_lawaai_voor_v2',
    'tkl_alc_voor_v2',
    'tkl_angst_voor_v2',
    'tkl_droog_voor_v2',
    'tkl_nekpijn_voor_v2',
    'tkl_nekstijf_voor_v2',
    'tkl_arm_voor_v2',
    'tkl_jeuk_voor_v2',
]

HISC_6_months_TBI_post = [
    'tkl_hp_na_v2',
    'tkl_duizel_na_v2',
    'tkl_evenw_na_v2',
    'tkl_oor_na_v2',
    'tkl_gehoor_na_v2',
    'tkl_slaap_na_v2',
    'tkl_inslaap_na_v2',
    'tkl_doorslaap_na_v2',
    'tkl_moe_na_v2',
    'tkl_vergeet_na_v2',
    'tkl_conc_na_v2',
    'tkl_traag_na_v2',
    'tkl_prik_na_v2',
    'tkl_lawaai_na_v2',
    'tkl_alc_na_v2',
    'tkl_angst_na_v2',
    'tkl_droog_na_v2',
    'tkl_nekpijn_na_v2',
    'tkl_nekstijf_na_v2',
    'tkl_arm_na_v2',
    'tkl_jeuk_na_v2',
]

HISC_2_weeks_HC = [
    'tkl_hp_hc',
    'tkl_duizel_hc',
    'tkl_evenw_hc',
    'tkl_oor_hc',
    'tkl_gehoor_hc',
    'tkl_slaap_hc',
    'tkl_inslaap_hc',
    'tkl_doorslaap_hc',
    'tkl_moe_hc',
    'tkl_vergeet_hc',
    'tkl_conc_hc',
    'tkl_traag_hc',
    'tkl_prik_hc',
    'tkl_lawaai_hc',
    'tkl_alc_hc',
    'tkl_angst_tkl_hc',
    'tkl_droog_hc',
    'tkl_nekpijn_hc',
    'tkl_nekstijf_hc',
    'tkl_arm_hc',
    'tkl_jeuk_hc',   
]

HISC_6_months_HC = [
    'tkl_hp_v2_hc',
    'tkl_duizel_v2_hc',
    'tkl_evenw_v2_hc',
    'tkl_oor_v2_hc',
    'tkl_gehoor_v2_hc',
    'tkl_slaap_tkl_v2_hc',
    'tkl_inslaap_v2_hc',
    'tkl_doorslaap_v2_hc',
    'tkl_moe_v2_hc',
    'tkl_vergeet_v2_hc',
    'tkl_conc_v2_hc',
    'tkl_traag_v2_hc',
    'tkl_prik_v2_hc',
    'tkl_lawaai_v2_hc',
    'tkl_alc_v2_hc',
    'tkl_angst_tkl_v2_hc',
    'tkl_droog_v2_hc',
    'tkl_nekpijn_v2_hc',
    'tkl_nekstijf_v2_hc',
    'tkl_arm_v2_hc',
    'tkl_jeuk_v2_hc',   
]

neo_tbi = [
    'neo_tobber',
    'neo_mensen',
    'neo_dagdromen',
    'neo_hoffelijk',
    'neo_spullen',
    'neo_mindere',
    'neo_lach',
    'neo_manier',
    'neo_mening',
    'neo_oppep',
    'neo_eronderdoor',
    'neo_opgewekt_persoon',
    'neo_intrigeer',
    'neo_egoistisch',
    'neo_systematisch',
    'neo_eenzaam',
    'neo_leuk_praten',
    'neo_leerlingen',
    'neo_samenwerken',
    'neo_gewetensvol',
    'neo_zenuwachtig',
    'neo_beleven',
    'neo_poezie',
    'neo_cynisch',
    'neo_doelen',
    'neo_waardeloos',
    'neo_alleen_doen',
    'neo_gerechten',
    'neo_gebruiken',
    'neo_verknoei',
    'neo_zorgelijk',
    'neo_energie',
    'neo_omgeving',
    'neo_graag_mogen',
    'neo_doel_bereik',
    'neo_kwaad_behandel',
    'neo_levendig',
    'neo_moreel',
    'neo_koel',
    'neo_belofte',
    'neo_opgeven',
    'neo_optimist',
    'neo_rilling',
    'neo_zakelijk',
    'neo_betrouwbaar',
    'neo_verdrietig',
    'neo_jachtig',
    'neo_universum',
    'neo_attent',
    'neo_productief',
    'neo_hulpeloos',
    'neo_actief',
    'neo_intellectueel',
    'neo_merken',
    'neo_op_orde',
    'neo_schaam',
    'neo_eigen_gang',
    'neo_theorie',
    'neo_manipuleren',
    'neo_uitblinken',
]

neo_hc = [
        'neo_tobber_hc',
    'neo_mensen_hc',
    'neo_dagdromen_hc',
    'neo_hoffelijk_hc',
    'neo_spullen_hc',
    'neo_mindere_hc',
    'neo_lach_hc',
    'neo_manier_hc',
    'neo_mening_hc',
    'neo_oppep_hc',
    'neo_eronderdoor_hc',
    'neo_opgewekt_persoon_hc',
    'neo_intrigeer_hc',
    'neo_egoistisch_hc',
    'neo_systematisch_hc',
    'neo_eenzaam_hc',
    'neo_leuk_praten_hc',
    'neo_leerlingen_hc',
    'neo_samenwerken_hc',
    'neo_gewetensvol_hc',
    'neo_zenuwachtig_hc',
    'neo_beleven_hc',
    'neo_poezie_hc',
    'neo_cynisch_hc',
    'neo_doelen_hc',
    'neo_waardeloos_hc',
    'neo_alleen_doen_hc',
    'neo_gerechten_hc',
    'neo_gebruiken_hc',
    'neo_verknoei_hc',
    'neo_zorgelijk_hc',
    'neo_energie_hc',
    'neo_omgeving_hc',
    'neo_graag_mogen_hc',
    'neo_doel_bereik_hc',
    'neo_kwaad_behandel_hc',
    'neo_levendig_hc',
    'neo_moreel_hc',
    'neo_koel_hc',
    'neo_belofte_hc',
    'neo_opgeven_hc',
    'neo_optimist_hc',
    'neo_rilling_hc',
    'neo_zakelijk_hc',
    'neo_betrouwbaar_hc',
    'neo_verdrietig_hc',
    'neo_jachtig_hc',
    'neo_universum_hc',
    'neo_attent_hc',
    'neo_productief_hc',
    'neo_hulpeloos_hc',
    'neo_actief_hc',
    'neo_intellectueel_hc',
    'neo_merken_hc',
    'neo_op_orde_hc',
    'neo_schaam_hc',
    'neo_eigen_gang_hc',
    'neo_theorie_hc',
    'neo_manipuleren_hc',
    'neo_uitblinken_hc'
]

gose_tbi = [
    'gose_opdrachten',
    'gose_hulp',
    'gose_hulp_vaak',
    'gose_onafh',
    'gose_boodschap',
    'gose_boodschap_voor',
    'gose_buurt',
    'gose_buurt_voor',
    'gose_werk_school',
    'gose_arbeid',
    'gose_werk_voor',
    'gose_sociaal',
    'gose_beperk_vrije_tijd',
    'gose_omgang',
    'gose_psych_prob',
    'gose_psych_prob_vaak',
    'gose_psych_prob_anders',
    'gose_klachten',
    'gose_klachten_voor',
    'gose_klachten_oorzaak',
]

gose_hc = [
    'gose_opdrachten_hc',
    'gose_hulp_hc',
    'gose_hulp_vaak_hc',
    'gose_onafh_hc',
    'gose_boodschap_hc',
    'gose_boodschap_voor_hc',
    'gose_buurt_hc',
    'gose_buurt_voor_hc',
    'gose_werk_school_hc',
    'gose_arbeid_hc',
    'gose_werk_voor_hc',
    'gose_sociaal_hc',
    'gose_beperk_vrije_tijd_hc',
    'gose_omgang_hc',
    'gose_psych_prob_hc',
    'gose_psych_prob_vaak_hc',
    'gose_psych_prob_anders_hc',
    'gose_klachten_hc',
    'gose_klachten_voor_hc',
    'gose_klacht_oorzaak_hc',
]

ies_questions = [
    'ies_denken_v2',
    'ies_van_streek_v2',
    'ies_geheugen_ban_v2',
    'ies_slaap_v2',
    'ies_gevoelens_v2',
    'ies_droom_v2',
    'ies_uit_de_weg_v2',
    'ies_niet_echt_v2',
    'ies_praten_v2',
    'ies_beelden_v2',
    'ies_andere_dingen_v2',
    'ies_rekening_v2',
    'ies_niet_denken_v2',
    'ies_herinnering_v2',
    'ies_verdoofd_v2',
]

reorder_list = [
    'record_id',
    'lab_id',
    'mri_id',
    'hair_cortisol_participation',
    'eeg_participation',
    'group',
    'age',
    'gender',
    'centre',
    'ct_abnormalities',
    'marshall_score',
    'conclusion_radiologist_ct',
    'injury_mechanism',
    'gcs',
    'loc',
    'pta',
    'hospital_admission',
    'ais_head',
    'extracranial_injury',
    'iss',
    'alcohol_intoxication',
    'units_alcohol',
    'trauma_capitis',
    'ct_abnormality_cervical_spine',
    'ct_abnormality_type_cervical_spine',
    'operation',
    'operation_type',
    'hads_a_2_weeks',
    'hads_d_2_weeks',
    'hads_a_6_months',
    'hads_d_6_months',
    'hisc_total_change_2_weeks',
    'hisc_number_of_items_increase_2_weeks',
    'hisc_total_change_6_months',
    'hisc_number_of_items_increase_6_months',
    'hisc_total_score_2_weeks_pre',
    'hisc_number_of_symptoms_2_weeks_pre',
    'hisc_total_score_2_weeks_post',
    'hisc_number_of_symptoms_2_weeks_post',
    'hisc_total_score_6_months_pre',
    'hisc_number_of_symptoms_6_months_pre',
    'hisc_total_score_6_months_post',
    'hisc_number_of_symptoms_6_months_post',
    'neo_n',
    'neo_e',
    'neo_o',
    'neo_a',
    'neo_c',
    'ies_sum',
    'gose_6_months',
    'ethanol_conc_admission',
    'anticoagulants_type', 
    'anticoagulants_additional',
    'inflammation_history',
    'inflammation_history_meds',
    'hypertension_history_medical_file',
    'diabetes_history_medical_file',
    'hyperlipidaemia_history_medical_file',
    'copd_astma_history_medical_file',
    'corticosteroid_use_medical_file',
    'handedness',
    'education_type',
    'occupation_status',
    'medications_use',
    'medications_use_type',
    'smoker',
    'daily_cigarette_amount',
    'alcohol_use',
    'alcohol_amount',
    'drug_use',
    'drug_use_amount',
    'previous_tbi',
    'physical_symptoms',
    'physical_symptoms_type',
    'physical_symptoms_treatment',
    'physical_symptoms_treater',
    'psychological_symptoms',
    'psychological_symptoms_type',
    'psychological_symptoms_treatment',
    'psychological_symptoms_treater',
    'time_to_v1_minutes',
    'time_to_v2_days',
    'time_to_mri_days',
    'time_to_eeg_1_minutes',
    'time_to_eeg_2_days',
    'time_to_hair_days',
    'time_to_v1_questionnaire_healthy_days',
    'time_to_v2_questionnaire_healthy_days',
    'time_to_v2_questionnaire_control_days',
]

rename_dict = {
    'nummer_mri': 'mri_id',
    'id_lab': 'lab_id',
    'centrum': 'centre',
    'ct_abn': 'ct_abnormalities',
    'marshall': 'marshall_score',
    'concl_radio_ct': 'conclusion_radiologist_ct',
    'ongevalsmechanisme': 'injury_mechanism',
    'opname_yes_no': 'hospital_admission',
    'ais_hoofd': 'ais_head',
    'extracran': 'extracranial_injury',
    'iss_total': 'iss',
    'ctcwk1': 'ct_abnormality_cervical_spine',
    'ctcwk2': 'ct_abnormality_type_cervical_spine',
    'operatie1': 'operation',
    'operatie2': 'operation_type',
    'NEO_N': 'neo_n',
    'NEO_E': 'neo_e',
    'NEO_O': 'neo_o',
    'NEO_A': 'neo_a',
    'NEO_C': 'neo_c',
    'ethanol': 'ethanol_conc_admission',
    'antistol': 'anticoagulants_type',
    'overig_antistol_what': 'anticoagulants_additional',
    'inflamm_vg': 'inflammation_history',
    'med_inflamm1': "inflammation_history_meds",
    'ht_dossier': 'hypertension_history_medical_file',
    'dm_dossier': 'diabetes_history_medical_file',
    'hyperlip_dossier': 'hyperlipidaemia_history_medical_file',
    'copd_astma_dossier': 'copd_astma_history_medical_file',
    'cortico_dossier': 'corticosteroid_use_medical_file',
    'cortisoldeelname': 'hair_cortisol_participation',
    'eeg_deelname': 'eeg_participation',
    'edu': 'education_type',
    'werk_studie': 'occupation_status',
    'meds': 'medications_use',
    'meds_type': 'medications_use_type',
    'roken': 'smoker',
    'roken_hoeveel': 'daily_cigarette_amount',
    'alcohol': 'alcohol_use',
    'alcohol_hoeveel': 'alcohol_amount',
    'drugs': 'drug_use',
    'drugs_hoeveel': 'drug_use_amount',
    'eerder_tbi': 'previous_tbi',
    'lichaam': 'physical_symptoms',
    'lichaam_kl': 'physical_symptoms_type',
    'lichaam_behandeling': 'physical_symptoms_treatment',
    'lichaam_behandelaar': 'physical_symptoms_treater',
    'psych': 'psychological_symptoms',
    'psych_kl': 'psychological_symptoms_type',
    'psych_behandeling': 'psychological_symptoms_treatment',
    'psych_behandelaar': 'psychological_symptoms_treater',
    'psych_opname': 'admission_for_psycho_symptoms',
    'alcohol_ongeval': 'alcohol_intoxication',
    'eenheden_alc': 'units_alcohol', 
    'nummermri': 'mri_id',
}

columns_to_replace = [
    'handedness',
    'edu',
    'werk_studie',
    'meds',
    'meds_type', 
    'roken', 
    'roken_hoeveel', 
    'alcohol', 
    'alcohol_hoeveel', 
    'drugs', 
    'drugs_hoeveel', 
    'lichaam', 
    'lichaam_kl', 
    'lichaam_behandeling', 
    'lichaam_behandelaar', 
    'psych', 
    'psych_kl', 
    'psych_behandeling', 
    'psych_behandelaar', 
    'psych_opname'
    ]

columns_to_remove = [
    'dataofinjury', 
    'mrideelname', 
    'tijd_ongeval', 
    'time_of_injury', 
    'v1_datum', 
    'afnametijdv1', 
    'time_of_v1', 
    'datumv2', 
    'time_of_v2', 
    'datummri', 
    'time_of_mri', 
    'datumeeg1', 
    'datumeeg2', 
    'time_of_eeg_1', 
    'time_of_eeg_2', 
    'datum_haar', 
    'time_of_hair', 
    'woonplaats', 
    'email_yes_no', 
    'email', 
    'ptascorelijst', 
    'dataofinjury', 
    'demographics_and_injury_characteristics_complete', 
    'drugs_ongeval', 
    'drugs_ongeval_hoeveel', 
    'tijd_ongeval', 
    'v1_datum', 
    'afnametijdv1', 
    'v2_afname', 
    'datumv2', 
    'extra_opm_gcs', 
    'elektrischefiets', 
    'helm', 
    'opname_dagen', 
    'inflamm_vg2', 
    'med_inflamm2', 
    'datumeeg1', 
    'tijdeeg1', 
    'datumeeg2', 
    'datummri', 
    'datum_haar', 
    'speeksel', 
    'leeftijd', 
    'injury_characteristics_extra_complete', 
    'werk_functie', 
    'woonsituatie', 
    'vrije_tijd', 
    'sport_uren', 
    'vragenlijsten_deel_1_complete', 
    'vragenlijsten_deel_2_complete', 
    'leeftijd_hc', 
    'vragenlijsten_deel_2_voor_gezonde_proefpersonen_complete', 
    'vragenlijsten_deel_1_voor_gezonde_proefpersonen_complete', 
    'handedness_hc', 
    'edu_hc', 
    'werk_studie_hc', 
    'werk_functie_hc', 
    'woonsituatie_hc', 
    'vrije_tijd_hc', 
    'sport_uren_hc', 
    'meds_hc', 
    'meds_type_hc', 
    'roken_hc', 
    'roken_hoeveel_hc', 
    'alcohol_hc', 
    'alcohol_hoeveel_hc', 
    'drugs_hc', 
    'drugs_hoeveel_hc', 
    'lichaam_hc', 
    'lichaam_kl_hc', 
    'lichaam_behandeling_hc', 
    'lichaam_behandelaar_hc', 
    'psych_hc', 
    'psych_kl_hc', 
    'psych_behandeling_hc', 
    'psych_behandelaar_hc', 
    'psych_opname_hc',
    'vragenlijsten_deel_1_voor_gezonde_proefpersonen_timestamp',
    'vragenlijsten_deel_2_voor_gezonde_proefpersonen_timestamp',
    'redcap_survey_identifier',
    'demographics_and_injury_characteristics_timestamp',
    # 'vragenlijsten_deel_1_timestamp',
    # 'vragenlijsten_deel_2_timestamp',
    # 'time_of_v1_quest_healthy',
    # 'time_of_v1_quest_control',
    # 'time_of_v2_quest_healthy',
    # 'time_of_v2_quest_control'
    ]

biomarker_llod = {
    'il6': ['<0.06', 0.06, 'x', -1, '<0.633', 0.633], 
    'il8': ['<0.07', 0.07, 'x', -1, "<0.59", 0.59], 
    'il10': ['<0.051', 0.051, 'x', -1, '<0.298', 0.298], 
    'nfl': ['<5.2', 5.2, '>12500', 12500]
    }