---
title: "miRNA_expression_analysis"
author: "Koen Visser"
date: "`r Sys.Date()`"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(clusterProfiler)
library(org.Hs.eg.db)
library(enrichR)
library(enrichplot)
library(tibble)
library(dplyr)
library(ggplot2)
library(ggraph)
library(stringr)
```

```{r}
target_data <- read.delim("~/Documents/phd/biomarkers/mirna/Summary_Counts.default_predictions.txt")
```

```{r}
my_mirnas_ct_pred <- c('hsa-miR-760', 'hsa-miR-324-5p', 'hsa-miR-155-5p', 'hsa-miR-1270', 'hsa-miR-3127-5p')

my_targets <- subset(target_data, Representative.miRNA %in% my_mirnas_ct_pred)

strong_targets <- subset(my_targets, `Cumulative.weighted.context...score` < -0.5)

cat("Total targets:", nrow(my_targets), "\n")

# Number of strong targets
cat("Strong targets (score < -0.5):", nrow(strong_targets), "\n")

gene_symbols_ct <- unique(my_targets$Gene.Symbol)

write.table(gene_symbols_ct, "~/Documents/phd/biomarkers/mirna/gene_symbols_ct.txt", quote=FALSE, row.names=FALSE, col.names=FALSE)

entrez_ids_ct <- bitr(gene_symbols_ct, fromType = "SYMBOL", toType = "ENTREZID", OrgDb = org.Hs.eg.db)

go_results_ct <- enrichGO(
  gene = entrez_ids_ct$ENTREZID,
  OrgDb = org.Hs.eg.db,
  ont = "BP",
  pAdjustMethod = "BH",
  pvalueCutoff = 0.05,
  qvalueCutoff = 0.2,
  readable = TRUE
)

# View results
head(go_results_ct, 30)
```

```{r}
p <- dotplot(go_results_ct, label_format=100, showCategory=10)
print(p)
ggsave("~/Documents/phd/biomarkers/mirna/figures/goplot_ct.svg", plot = p, width = 160, height = 120, units = "mm", dpi = 300)

p1 <- cnetplot(go_results_ct, showCategory = 2, circular=TRUE, colorEdge=TRUE)
print(p1)
ggsave("~/Documents/phd/biomarkers/mirna/figures/cnet_ct.svg", plot = p1, width = 200, height = 120, units = "mm", dpi = 300)

emap <- emapplot(pairwise_termsim(go_results_ct), showCategory = 10, layout = "kk")
print(emap)
```

```{r}
# Use Reactome pathway database
reactome_results <- enrichr(gene_symbols_ct, databases = "Reactome_Pathways_2024")
```
```{r}
# Filter significant pathways
reactome_sig <- subset(reactome_results[["Reactome_Pathways_2024"]], Adjusted.P.value < 0.05)

# Sort by p-value and select top 10
top10_reactome <- reactome_sig[order(reactome_sig$P.value), ][1:10, ]

# View more columns
top10_reactome[, c("Term", "P.value", "Adjusted.P.value", "Overlap", "Genes")]

top10_reactome$Term <- str_wrap(top10_reactome$Term, width = 45)

# Clean up names if needed
top10_reactome$Term <- factor(top10_reactome$Term, levels = rev(top10_reactome$Term))

head(top10_reactome)

# Plot
ct_plot = ggplot(top10_reactome, aes(x = Term, y = -log10(P.value))) +
  geom_col(fill = "steelblue") +
  coord_flip() +
  labs(
    x = "Pathway",
    y = "-log10(P-value)"
  ) +
  theme_minimal(base_size = 12) +
  theme(axis.text.y = element_text(color="black"))

print(ct_plot)

ggsave("~/Documents/phd/biomarkers/mirna/figures/reactome_ct.svg", plot = ct_plot, width = 160, height = 120, units = "mm", dpi = 300)
```

```{r}
my_mirnas_gose_pred <- c('hsa-miR-330-3p', 'hsa-miR-3127-5p', 'hsa-miR-301a-3p', 'hsa-miR-197-5p', 'hsa-miR-11400')

my_targets_gose <- subset(target_data, Representative.miRNA %in% my_mirnas_gose_pred)

strong_targets_gose <- subset(my_targets_gose, `Cumulative.weighted.context...score` < -0.5)

cat("Total targets:", nrow(my_targets_gose), "\n")

# Number of strong targets
cat("Strong targets (score < -0.5):", nrow(strong_targets_gose), "\n")

gene_symbols_gose <- unique(my_targets_gose$Gene.Symbol)

write.table(gene_symbols_gose, "~/Documents/phd/biomarkers/mirna/gene_symbols_gose.txt", quote=FALSE, row.names=FALSE, col.names=FALSE)

entrez_ids_gose <- bitr(gene_symbols_gose, fromType = "SYMBOL", toType = "ENTREZID", OrgDb = org.Hs.eg.db)

go_results_gose <- enrichGO(
  gene = entrez_ids_gose$ENTREZID,
  OrgDb = org.Hs.eg.db,
  ont = "BP",
  pAdjustMethod = "BH",
  pvalueCutoff = 0.05,
  qvalueCutoff = 0.2,
  readable = TRUE
)

# View results
head(go_results_gose, 30)
```
```{r}
p_gose <- dotplot(go_results_gose, label_format=100, showCategory=10)
print(p_gose)
ggsave("~/Documents/phd/biomarkers/mirna/figures/goplot_gose.svg", plot = p_gose, width = 160, height = 120, units = "mm", dpi = 300)

p1_gose <- cnetplot(go_results_gose, showCategory = 2, circular=TRUE, colorEdge=TRUE)
print(p1_gose)
ggsave("~/Documents/phd/biomarkers/mirna/figures/cnet_gose.svg", plot = p1_gose, width = 200, height = 120, units = "mm", dpi = 300)

emap_gose <- emapplot(pairwise_termsim(go_results_gose), showCategory = 10, layout = "kk")
print(emap_gose)
```

```{r}
# Use Reactome pathway database
reactome_results_gose <- enrichr(gene_symbols_gose, databases = "Reactome_Pathways_2024")
```

```{r}
# Filter significant pathways
reactome_sig_gose <- subset(reactome_results_gose[["Reactome_Pathways_2024"]], Adjusted.P.value < 0.05)

# Sort by p-value and select top 10
top10_reactome_gose <- reactome_sig_gose[order(reactome_sig_gose$Adjusted.P.value), ][1:10, ]

# View more columns
top10_reactome_gose[, c("Term", "P.value", "Adjusted.P.value", "Overlap", "Genes")]

top10_reactome_gose$Term <- str_wrap(top10_reactome_gose$Term, width = 45)

# Clean up names if needed
top10_reactome_gose$Term <- factor(top10_reactome_gose$Term, levels = rev(top10_reactome_gose$Term))

head(top10_reactome_gose)

# Plot
gose_plot = ggplot(top10_reactome_gose, aes(x = Term, y = -log10(P.value))) +
  geom_col(fill = "steelblue") +
  coord_flip() +
  labs(
    x = "Pathway",
    y = "-log10(P-value)"
  ) +
  theme_minimal(base_size = 12) +
  theme(axis.text.y = element_text(color="black"))

print(gose_plot)

ggsave("~/Documents/phd/biomarkers/mirna/figures/reactome_gose.svg", plot = gose_plot, width = 160, height = 120, units = "mm", dpi = 300)
```